services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432
    restart: unless-stopped
  web:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - ENABLE_PROMETHEUS=true
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/staticfiles
      - media:/media
    restart: unless-stopped
volumes:
  db-data:
  staticfiles:
  media:
