server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'
    pipeline_stages:
      - docker: {}
      - drop:
          expression: '"GET /metrics"'
      - drop:
          expression: '"GET /api/v1/health/"'
      - json:
          expressions:
            asctime: asctime
            levelname: levelname
            name: name
            message: message
            request_id: request_id
            path: path
            status_code: status_code
      - labels:
          level: levelname
          logger: name
          service_name: service_name
          request_id: request_id

