# Generated by Django 4.2.23 on 2025-07-27 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxMaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Box Maker',
                'verbose_name_plural': 'Box Makers',
                'db_table': 'box_makers',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'db_table': 'printers',
            },
        ),
        migrations.CreateModel(
            name='TracingStudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracing Studio',
                'verbose_name_plural': 'Tracing Studios',
                'db_table': 'tracing_studios',
            },
        ),
        migrations.CreateModel(
            name='PrintingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('print_quantity', models.IntegerField()),
                ('total_printing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('printing_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=11)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_jobs', to='orders.orderitem')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_jobs', to='production.printer')),
                ('tracing_studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_jobs', to='production.tracingstudio')),
            ],
            options={
                'verbose_name': 'Printing Job',
                'verbose_name_plural': 'Printing Jobs',
                'db_table': 'printing_jobs',
            },
        ),
        migrations.CreateModel(
            name='BoxOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('box_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Custom')], max_length=8)),
                ('box_quantity', models.IntegerField()),
                ('total_box_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_orders', to='production.boxmaker')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_orders', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Box Order',
                'verbose_name_plural': 'Box Orders',
                'db_table': 'box_orders',
            },
        ),
    ]
