# Generated by Django 5.2.4 on 2025-08-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printingjob",
            name="printing_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("IN_TRACING", "In Tracing"), ("IN_PRINTING", "In Printing"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=11,
            ),
        ),
    ]
