# Generated by Django 5.2.4 on 2025-08-03 07:12

from django.db import migrations


def update_printing_status_forward(apps, schema_editor):
    """Convert IN_PROGRESS to IN_PRINTING for existing records"""
    PrintingJob = apps.get_model("production", "PrintingJob")

    # Update all IN_PROGRESS records to IN_PRINTING
    PrintingJob.objects.filter(printing_status="IN_PROGRESS").update(printing_status="IN_PRINTING")


def update_printing_status_reverse(apps, schema_editor):
    """Convert IN_PRINTING back to IN_PROGRESS for rollback"""
    PrintingJob = apps.get_model("production", "PrintingJob")

    # Update all IN_PRINTING records back to IN_PROGRESS
    PrintingJob.objects.filter(printing_status="IN_PRINTING").update(printing_status="IN_PROGRESS")


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0002_update_printing_status_enum"),
    ]

    operations = [
        migrations.RunPython(
            update_printing_status_forward,
            update_printing_status_reverse,
        ),
    ]
