# Generated by Django 5.2.4 on 2025-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0003_data_migration_printing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxorder",
            name="total_box_expense",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printingjob",
            name="total_printing_expense",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printingjob",
            name="total_tracing_expense",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
