# Generated by Django 5.2.4 on 2025-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_boxorder_total_box_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxorder",
            name="total_box_expense",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="printingjob",
            name="total_printing_expense",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="printingjob",
            name="total_tracing_expense",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
