# Generated by Django 5.2.4 on 2025-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_alter_boxorder_total_box_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printingjob",
            name="impressions",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
