# Generated by Django 5.2.4 on 2025-10-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_printingjob_impressions"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxorder",
            name="box_maker_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="printingjob",
            name="printer_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="printingjob",
            name="tracing_studio_paid",
            field=models.BooleanField(default=False),
        ),
    ]
