# Generated by Django 5.2.4 on 2025-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_boxorder_box_maker_paid_printingjob_printer_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boxorder",
            name="box_maker_paid",
        ),
        migrations.RemoveField(
            model_name="printingjob",
            name="printer_paid",
        ),
        migrations.RemoveField(
            model_name="printingjob",
            name="tracing_studio_paid",
        ),
        migrations.AddField(
            model_name="boxorder",
            name="box_maker_vendor_status",
            field=models.CharField(choices=[("PENDING", "Pending"), ("DELIVERED", "Delivered"), ("PAID", "Paid")], default="PENDING", max_length=11),
        ),
        migrations.AddField(
            model_name="printingjob",
            name="printer_vendor_status",
            field=models.CharField(choices=[("PENDING", "Pending"), ("DELIVERED", "Delivered"), ("PAID", "Paid")], default="PENDING", max_length=11),
        ),
        migrations.AddField(
            model_name="printingjob",
            name="tracing_vendor_status",
            field=models.CharField(choices=[("PENDING", "Pending"), ("DELIVERED", "Delivered"), ("PAID", "Paid")], default="PENDING", max_length=11),
        ),
    ]
