# Generated by Django 5.2.4 on 2025-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(choices=[("ADMIN", "Admin"), ("MANAGER", "Manager"), ("SALES", "Sales")], default="SALES", max_length=11),
        ),
    ]
