# Generated by Django 4.2.23 on 2025-07-27 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="order_item",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_transactions", to="orders.orderitem"
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="staff",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_transactions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="card",
            name="vendor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cards", to="inventory.vendor"),
        ),
    ]
