# Generated by Django 5.2.4 on 2025-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single"),
                    ("BIRTHDAY", "Birthday"),
                    ("MUNDAN", "Mundan"),
                    ("CARRY_BAG", "CarryBag"),
                    ("THREE_FOLD", "ThreeFold"),
                    ("FIVE_FOLD", "FiveFold"),
                    ("ENVELOPE_11X5", "Envelope11x5"),
                    ("ENVELOPE_9X7", "Envelope9x7"),
                    ("JUMBO", "Jumbo"),
                    ("BOX", "Box"),
                    ("PADDING", "Padding"),
                    ("URDU_ENVELOPE_11X5", "UrduEnvelope11x5"),
                    ("URDU_ENVELOPE_9X7", "UrduEnvelope9x7"),
                    ("URDU_CARRY_BAG", "UrduCarryBag"),
                    ("URDU_JUMBO", "UrduJumbo"),
                    ("URDU_BOX", "UrduBox"),
                    ("URDU_PADDING", "UrduPadding"),
                ],
                db_index=True,
                default="ENVELOPE_11X5",
                max_length=32,
            ),
        ),
    ]
