# Generated by Django 5.2.4 on 2025-09-17 17:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("endpoint", models.CharField(max_length=255)),
                ("request_method", models.CharField(max_length=255)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("response_size_bytes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Audit Log",
                "verbose_name_plural": "API Audit Logs",
                "db_table": "api_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=50)),
                ("model_id", models.UUIDField()),
                ("action", models.CharField(choices=[("CREATE", "Create"), ("UPDATE", "Update"), ("DELETE", "Delete")], max_length=20)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("actor_user_agent", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(blank=True, choices=[("API", "API"), ("JOB", "Job"), ("ADMIN", "Admin"), ("SYSTEM", "System")], max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="model_audit_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Model Audit Log",
                "verbose_name_plural": "Model Audit Logs",
                "db_table": "model_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.AddIndex(
            model_name="apiauditlog",
            index=models.Index(fields=["endpoint", "request_method", "created_at"], name="idx_aal_endpoint_method_time"),
        ),
        migrations.AddIndex(
            model_name="apiauditlog",
            index=models.Index(fields=["status_code", "created_at"], name="idx_aal_status_time"),
        ),
        migrations.AddIndex(
            model_name="apiauditlog",
            index=models.Index(fields=["staff", "created_at"], name="idx_aal_staff_time"),
        ),
        migrations.AddIndex(
            model_name="modelauditlog",
            index=models.Index(fields=["model_name", "model_id", "created_at"], name="idx_mal_model_time"),
        ),
        migrations.AddIndex(
            model_name="modelauditlog",
            index=models.Index(fields=["staff", "created_at"], name="idx_mal_staff_time"),
        ),
        migrations.AddIndex(
            model_name="modelauditlog",
            index=models.Index(fields=["action", "created_at"], name="idx_mal_action_time"),
        ),
    ]
