# Generated by Django 5.2.4 on 2025-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="X weds Y", max_length=255),
            preserve_default=False,
        ),
    ]
