# Generated by Django 5.2.4 on 2025-09-23 15:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrderItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("DIGITAL_CARD", "Digital Card"),
                            ("ABHINANDAN_PATR", "Abhinandan Patr"),
                            ("CAR_POSTER", "Car Poster"),
                            ("DIGITAL_VISITING_CARD", "Digital Visiting Card"),
                        ],
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "procurement_status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ORDERED", "Ordered"),
                            ("RECEIVED", "Received"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=11,
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_expense", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_items", to="orders.order")),
            ],
            options={
                "verbose_name": "Service Order Item",
                "verbose_name_plural": "Service Order Items",
                "db_table": "service_order_items",
            },
        ),
    ]
