# Generated by Django 5.2.4 on 2025-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_serviceorderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("READY", "Ready"),
                    ("DELIVERED", "Delivered"),
                    ("FULLY_PAID", "Fully Paid"),
                ],
                default="CONFIRMED",
                max_length=11,
            ),
        ),
    ]
