# Generated by Django 5.2.4 on 2025-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("DIGITAL_CARD", "Digital Card"),
                    ("ABHINANDAN_PATR", "Abhinandan Patr"),
                    ("CAR_POSTER", "Car Poster"),
                    ("DIGITAL_VISITING_CARD", "Digital Visiting Card"),
                    ("PRINTING_SERVICE", "Printing Service"),
                    ("BOX_SERVICE", "Box Service"),
                ],
                max_length=255,
            ),
        ),
    ]
